version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
  #  pre_build:
  #    commands:
  #      - echo Entered the pre_build phase...
  #    finally:
  #      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn package
  #    finally:
  #      - echo This always runs even if the install command fails
  #  post_build:
  #    commands:
  #      - echo Entered the post_build phase...
  #      - echo Build completed on `date`

artifacts:
  files:
    - target/sonar-example-plugin-0.1-SNAPSHOT.jar
